apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: CLOUDFLARED_TOKEN{{ .Values.secretSuffix }}