apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-config
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  configuration: ""
  credentials:
    - filename: authentik-token
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: authentik-api-token
        key: token