apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.6.1
    helm:
      values: |
        releaseLabel: true
        serviceMonitor:
          enabled: true
          defaults:
            labels:
              release: kube-prometheus
          targets:
          - name: argocd
            url: http://argocd.jeremymr.dev/healthz  # The URL that blackbox will scrape
            interval: 60s                    # Scraping interval. Overrides value set in `defaults`
            scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
            module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
          - name: kleff
            url: https://kleff.io
            interval: 60s
            scrapeTimeout: 60s
            module: http_2xx
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
