name: kube-prometheus
namespace: monitoring
syncWave: "9"
repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
targetRevision: 83.6.0
values: |
  grafana:
    admin:
      existingSecret: "grafana-secret"
      userKey: admin-user
      passwordKey: admin-password