name: kube-prometheus
namespace: monitoring
syncWave: "9"
repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
targetRevision: 80.13.3
values: |
  alertmanager:
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'discord-receiver'
      receivers:
        - name: 'discord-receiver'
          discord_configs:
            - webhook_url: "https://discord.com/api/webhooks/1495225028097216582/gBumDncArzFma3cu2Vkm01KCrCvLZPfjVfnz2-Mj4Kz2A0rwr7nAOAtDIELF5nnAKaYK"
  grafana:
    sidecar:
      datasources:
        watchMethod: LIST
      dashboards:
        watchMethod: LIST
    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
        secretKeyRef:
          name: grafana-client-secret
          key: client-id
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-client-secret
          key: client-secret
    admin:
      existingSecret: "grafana-secret"
      userKey: admin-user
      passwordKey: admin-password
    grafana.ini:
      server:
        root_url: "https://grafana.jeremymr.dev"
      auth:
        signout_redirect_url: "https://auth.jeremymr.dev/application/o/grafana/end-session/"
        oauth_auto_login: true
      auth.generic_oauth:
        name: authentik
        enabled: true
        client_id: "${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}"
        client_secret: "${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
        scopes: "openid profile email"
        auth_url: "https://auth.jeremymr.dev/application/o/authorize/"
        token_url: "https://auth.jeremymr.dev/application/o/token/"
        api_url: "https://auth.jeremymr.dev/application/o/userinfo"
        email_attribute_path: email
        login_attribute_path: preferred_username
        name_attribute_path: name
        # Optionally map user groups to Grafana roles
        role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'