apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cert-manager
  namespace: cert-manager
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: CLOUDFLARE_API_TOKEN
