apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-password
  namespace: couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store

  target:
    name: couchdb-creds

  data:
    - secretKey: adminUsername
      remoteRef:
        key: COUCHDB_USERNAME

    - secretKey: adminPassword
      remoteRef:
        key: COUCHDB_PASSWORD

    - secretKey: erlangCookie
      remoteRef:
        key: COUCHDB_ERLANG_COOKIE

    - secretKey: cookietAuthSecret
      remoteRef:
        key: COUCHDB_COOKIE_AUTH_SECRET
