apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-loki-secret
  namespace: loki
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: garage-loki-secrets
    creationPolicy: Owner
  data:
  - secretKey: access-key-id
    remoteRef:
      key: GARAGE_LOKI_KEY_ID
  - secretKey: secret-access-key
    remoteRef:
      key: GARAGE_LOKI_SECRET_KEY

