apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-cr-creds
  namespace: portfolio
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: acr-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .acr_server }}": {
                "username": "{{ .acr_username }}",
                "password": "{{ .acr_password }}",
                "auth": "{{ (printf "%s:%s" .acr_username .acr_password) | b64enc }}"
              }
            }
          }
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: acr_server
    remoteRef:
      key: ACR_SERVER
  - secretKey: acr_username
    remoteRef:
      key: ACR_USERNAME
  - secretKey: acr_password
    remoteRef:
      key: ACR_PASSWORD1