apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: saima-cloudflare-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: saima-cloudflare-api-token-secret
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: SAIMA_CLOUDFLARE_API_TOKEN