apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-alertmanager-config
  namespace: monitoring
spec:
  route:
    groupBy:
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: discord-receiver
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
  receivers:
    - name: "null"
    - name: discord-receiver
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: discord-webhook-url
          sendResolved: true
  inhibitRules:
    - sourceMatch:
        - name: severity
          value: critical
      targetMatch:
        - name: severity
          value: "warning|info"
          regex: true
      equal:
        - namespace
        - alertname
    - sourceMatch:
        - name: severity
          value: warning
      targetMatch:
        - name: severity
          value: info
      equal:
        - namespace
        - alertname
    - sourceMatch:
        - name: alertname
          value: InfoInhibitor
      targetMatch:
        - name: severity
          value: info
      equal:
        - namespace
