name: envoy-gateway-config
namespace: envoy-gateway-system
syncWave: "11"
repoURL: https://github.com/jeremy-misola/GitOps-Homelab
targetRevision: develop
appPath: charts/infrastructure/envoy-gateway
