apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-Instrumentation
spec:
  exporter:
    # Point this to the Service created by your existing Collector Helm chart
    endpoint: http://existing-collector-service-name.namespace.svc.cluster.local:4317 
  propagators:
    - tracecontext
    - baggage
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest