apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  namespace: kleff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-service
  template:
    metadata:
      # annotations:
      #   instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: deployment-service
        paas: kleff
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
        - name: deployment-service
          image: kleff.azurecr.io/deployment-service:77364a9dc578579d74d63bd8eab5ff8ebf7a446d
          env:
            - name: AUDIT_SERVICE_URL
              value: http://api-gateway.kleff-deployment.svc.cluster.local:80/api/v1/projects/audit/internal
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://deployment-service-db:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: deployment_db_password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: kleff-deployment
spec:
  selector:
    app: deployment-service
  ports:
    - name: http
      port: 80
      targetPort: 8080