apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            namespace: external-secrets
            key: dopplerToken
