apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-external-secret
  namespace: backstage
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
  - secretKey: BACKEND_SECRET
    remoteRef:
      key: BACKSTAGE_BACKEND_SECRET
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: BACKSTAGE_POSTGRES_PASSWORD

