name: otel-instrumentation
namespace: opentelemetry-collector
syncWave: "16"
repoURL: https://github.com/jeremy-misola/GitOps-Homelab
targetRevision: develop
appPath: manifests/infra/opentelemetry-collector
