apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: default
  source:
    repoURL: https://github.com/jeremy-misola/GitOps-Homelab 
    targetRevision: HEAD
    path: charts/open-telemetry
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true