apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-lastfm-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: navidrome-lastfm-credentials
    creationPolicy: Owner
  data:
  - secretKey: apiKey
    remoteRef:
      key: NAVIDROME_LASTFM_API_KEY
  - secretKey: apiSecret
    remoteRef:
      key: NAVIDROME_LASTFM_API_SECRET
