gatewayName: dev-web
envSuffix: ""
authentikUrl: https://auth.jeremymr.dev

defaultRules:
  create: true
additionalPrometheusRulesMap:
  custom-alerts:
    groups:
      - name: custom-node-pressure
        rules:
          - alert: NodePressure
            expr: |
              max by (node, condition) (
                kube_node_status_condition{condition=~"MemoryPressure|DiskPressure|PIDPressure", status="true"} == 1
              )
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Node pressure on {{ $labels.node }}"
              description: "Node {{ $labels.node }} has {{ $labels.condition }} for more than 10 minutes."
      - name: custom-service-downtime
        rules:
          - alert: BlackboxTargetDown
            expr: probe_success{job=~"argocd|kleff"} == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Blackbox probe failed for {{ $labels.job }}"
              description: "The monitored target {{ $labels.job }} has been failing probes for more than 5 minutes."
alertmanager:
  secrets:
    - alertmanager-discord-webhook
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'discord-receiver'
      routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: 'null'
      - name: 'discord-receiver'
        discord_configs:
          - webhook_url_file: /etc/alertmanager/secrets/alertmanager-discord-webhook/discord-webhook-url
    templates:
      - '/etc/alertmanager/config/*.tmpl'
grafana:
  sidecar:
    datasources:
      watchMethod: LIST
    dashboards:
      watchMethod: LIST
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack-gateway.loki.svc.cluster.local:80
      jsonData:
        timeout: "300"
        maxLines: 1000
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: "1"
  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
      secretKeyRef:
        name: grafana-client-secret
        key: client-id
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-client-secret
        key: client-secret
  admin:
    existingSecret: "grafana-secret"
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    server:
      root_url: "https://grafana.jeremymr.dev"
    dataproxy:
      timeout: 300
    auth:
      signout_redirect_url: "https://auth-dev.jeremymr.dev/application/o/grafana/end-session/"
      oauth_auto_login: true
    auth.generic_oauth:
      name: authentik
      enabled: true
      client_id: "${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}"
      client_secret: "${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
      scopes: "openid profile email"
      auth_url: "https://auth-dev.jeremymr.dev/application/o/authorize/"
      token_url: "https://auth-dev.jeremymr.dev/application/o/token/"
      api_url: "https://auth-dev.jeremymr.dev/application/o/userinfo"
      email_attribute_path: email
      login_attribute_path: preferred_username
      name_attribute_path: name
      # Optionally map user groups to Grafana roles
      role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
