apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: saima-ghost-route
  namespace: ghost-saima
spec:
  parentRefs:
  - name: prod-web
    namespace: envoy-gateway-system
  hostnames:
    - saimachowdhury.ca
  rules:
  - backendRefs:
    - name: ghost-saima
      port: 80

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: saima-admin-ghost-route
  namespace: ghost-saima
spec:
  parentRefs:
  - name: prod-web
    namespace: envoy-gateway-system
  hostnames:
    - admin.saimachowdhury.ca
  rules:
  - backendRefs:
    - name: ghost-saima
      port: 80