apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-saima
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: misolarellinj06@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-saima
    solvers:
    - dns01:
        cloudflare:
          email: misolarellinj06@gmail.com
          apiTokenSecretRef:
            name: saima-cloudflare-api-token-secret
            key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-saima
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-saima
    solvers:
    - dns01:
        cloudflare:
          email: misolarellinj06@gmail.com
          apiTokenSecretRef:
            name: saima-cloudflare-api-token-secret
            key: api-token
