apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://apache.github.io/couchdb-helm
    chart: couchdb
    targetRevision: 4.6.2
    helm:
      values: |
        createAdminSecret: false
        extraSecretName: "couchdb-creds"
        adminPasswordKey: "adminUsername"
        adminPasswordKey: "adminPassword"
        cookieAuthSecretKey: "cookieAuthSecret"
        cookieAuthSecretKey: "erlangCookie"
        couchdbConfig:
          couchdb:
            uuid: $(curl https://www.uuidgenerator.net/api/version4 2>/dev/null | tr -d -)

  destination:
    server: https://kubernetes.default.svc
    namespace: couchdb
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

