apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pmoscode-helm.github.io/excalidraw/
    chart: excalidraw
    targetRevision: 0.18.0
  destination:
    server: https://kubernetes.default.svc
    namespace: excalidraw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
