apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 8.5.1
    helm:
      values: |
        nextcloud:
          host: nextcloud.tail36492e.ts.net
          trustedDomains: 
            - "nextcloud.tail36492e.ts.net"

          existingSecret:
            enabled: true
            secretName: nextcloud-creds
            usernameKey: usernameKey
            passwordKey: passwordKey

        persistence:
          enabled: true
          nextcloudData:
            enabled: true
            storageClass: longhorn
            size: 50gi


  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
