# APIs
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: authentik-oidc
  description: OIDC authentication API
spec:
  type: openapi
  lifecycle: production
  owner: team-platform
  system: homelab
  definition: |
    openapi: 3.0.1
    info:
      title: Authentik OIDC API
      version: 1.0.0
      description: OIDC authentication endpoints
    servers:
      - url: https://auth.jeremymr.dev/application/o/devdocs
    paths:
      /.well-known/openid-configuration:
        get:
          summary: OpenID Connect Discovery
          responses:
            '200':
              description: OpenID configuration document