# Organization and Teams
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default
  description: Default organization
spec:
  type: organization
  children: [team-platform]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-platform
  description: Platform Engineering Team
spec:
  type: team
  parent: default
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  description: Default guest user
spec:
  memberOf: [team-platform]
  profile:
    displayName: Guest User
    email: guest@example.com