apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: 'https://git.deuxfleurs.fr/Deuxfleurs/garage'
    targetRevision: HEAD
    path: script/helm/garage
    helm:
      values: |
        releaseName: garage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: garage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true