apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: 'https://datahub-local.github.io/garage-helm'
    chart: garage
    targetRevision: 0.2.1 # Match the version from the documentation provided
    helm:
      values: |
        deployment:
          replicaCount: 2

        persistence:
          enabled: true
          meta:
            storageClass: "longhorn"
            size: 500Mi
          data:
            storageClass: "longhorn"
            size: 10Gi

        clusterConfig:
          enabled: true
          layout:
            enabled: true
            zone: dc1
            capacity: 10Gi
          
          buckets:
            - loki-chunks
            - loki-ruler
            - loki-admin
          
          keys:
            loki-key:
              keyId: "GK000000000000000000000001" # Placeholder or your specific ID

        webui:
          enabled: true
        
        monitoring:
          metrics:
            enabled: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: garage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true