apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: 'https://datahub-local.github.io/garage-helm'
    chart: garage
    targetRevision: 0.2.1
    helm:
      values: |
        fullnameOverride: "garage"

        garage:
          secret:
            create: false
            name: "garage-loki-secrets" # Your ExternalSecret

        clusterConfig:
          enabled: true
          layout:
            enabled: true
            zone: dc1
            capacity: "10Gi"
          
          buckets:
            - name: loki-chunks
            - name: loki-ruler
            - name: loki-admin
          
          keys: {}

          extraCommands:
            - "key create loki-key"
            - "bucket allow loki-chunks --key loki-key --read --write"
            - "bucket allow loki-ruler --key loki-key --read --write"
            - "bucket allow loki-admin --key loki-key --read --write"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: garage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true