name: garage
namespace: garage
syncWave: "8"
repoURL: https://datahub-local.github.io/garage-helm
chart: garage
targetRevision: 0.2.1
values: |
  fullnameOverride: "garage"

  clusterConfig:
    enabled: true
    layout:
      enabled: true
      zone: dc1
      capacity: "10Gi"
    
    buckets:
      - name: loki-chunks
      - name: loki-ruler
      - name: loki-admin
    
    keys: {}

    extraCommands:
      - "key create loki-key"
      - "bucket allow loki-chunks --key loki-key --read --write"
      - "bucket allow loki-ruler --key loki-key --read --write"
      - "bucket allow loki-admin --key loki-key --read --write"