apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-service
  namespace: kleff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kleff-observability
  template:
    metadata:
      labels:
        app: kleff-observability
        paas: kleff
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
        - name: observability-service
          image: kleff.azurecr.io/observability-service:5393d2805f1a8725dc7203a4556c916c8b7f19bd
          env:
            # 1. Port Configuration
            - name: SERVER_PORT
              value: "8080"
            # 2. Auth Configuration (Mapped from old OAUTH2_ISSUER_URI)
            - name: PROMETHEUS_URL
              value: "http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090"
            - name: ENVIRONMENT
              value: "development"
            - name: LOKI_URL
              value: "http://loki-stack-gateway.loki.svc.cluster.local:80"
            - name: USER_SERVICE_URL
              value: "http://api-gateway.kleff-deployment.svc.cluster.local:80"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kleff-observability
  namespace: kleff-deployment
spec:
  selector:
    app: kleff-observability
  ports:
    - name: http
      port: 80
      targetPort: 8080
