fullnameOverride: navidrome

env:
  TZ: America/Toronto
  ND_LASTFM_ENABLED: "true"
  ND_LASTFM_APIKEY:
    valueFrom:
      secretKeyRef:
        name: navidrome-lastfm-credentials
        key: apiKey
  ND_LASTFM_SECRET:
    valueFrom:
      secretKeyRef:
        name: navidrome-lastfm-credentials
        key: apiSecret

persistence:
  config:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 2Gi
  music:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 50Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
