fullnameOverride: navidrome

env:
  TZ: America/Toronto

persistence:
  config:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
  music:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
