name: external-dns
namespace: external-dns
syncWave: "12"
repoURL: https://kubernetes-sigs.github.io/external-dns
chart: external-dns
targetRevision: 1.20.0
values: |
  provider: cloudflare

  policy: sync
  
  registry: txt
  txtOwnerId: paas-cluster

  domainFilters:
    - kleff.io
  
  serviceAccount:
    create: true
    name: external-dns
  rbac:
    create: true
  sources:
    - gateway-httproute

  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token-kleff
        key: api-token
