apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-route
  namespace: longhorn-system
spec:
  parentRefs:
  - name: "{{ .Values.gatewayName }}"
    namespace: envoy-gateway-system
  hostnames:
    - longhorn{{ .Values.envSuffix }}.jeremymr.dev
  rules:
  - backendRefs:
    - name: longhorn-frontend
      port: 80
