apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: "{{ .Values.gatewayName }}-config"
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: "{{ .Values.gatewayName }}-gateway-service"
        annotations:
          test-annotation: "test-value"
