apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quickplay-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: quickplay-credentials
    creationPolicy: Owner
  data:
  - secretKey: lidarrApiKey
    remoteRef:
      key: LIDARR_API_KEY
