apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-client-secret
  namespace: longhorn-system
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: homelab-client-secret
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: HOMELAB_AUTHENTIK_LONGHORN_CLIENT_SECRET