apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-api-token
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-api-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: AUTHENTIK_API_TOKEN