apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-otel
  namespace: opentelemetry-collector
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-otel
    creationPolicy: Owner
  data:
  - secretKey: basic-auth-header
    remoteRef:
      key: GRAFANA_CLOUD_BASIC_AUTH_HEADER
