apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-db-app
  namespace: portfolio
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: portfolio-db-app
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: PORTFOLIO_DB_USERNAME
  - secretKey: password
    remoteRef:
      key: PORTFOLIO_DB_PASSWORD