apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management-service
  namespace: kleff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-management-service
  template:
    metadata:
      labels:
        app: project-management-service
        paas: kleff
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
        - name: project-management-service
          image: kleff.azurecr.io/project-management-service:d7a453b7ae733c0429c0e55805c2aa3281c48be2
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: project-management-db-app
                  key: jdbc-uri
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project-management-db-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-management-db-app
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: project-management-service
  namespace: kleff-deployment
spec:
  selector:
    app: project-management-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
