apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: project-management-db
  namespace: kleff-deployment
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 1Gi
  bootstrap:
    initdb:
      database: mydb
      owner: postgres
  superuserSecret:
    name: project-management-db-credentials