apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: code-server-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gatewayName }}
    namespace: envoy-gateway-system
  hostnames:
    - code-server{{ .Values.envSuffix }}.jeremymr.dev
  rules:
  - backendRefs:
    - name: code-server
      port: 8080
