apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-monitor
  namespace: monitoring 
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      paas: kleff
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - path: /stats/prometheus

    targetPort: 15020
    honorLabels: true
    relabelings:
    - targetLabel: container
      replacement: istio-proxy