apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-monitor
  namespace: monitoring 
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio 
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - path: /stats/prometheus
    port: http-envoy-prom
    relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_container_name]
      regex: "istio-proxy"
