apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gatewayName }}
    namespace: envoy-gateway-system
    sectionName: minecraft
  rules:
  - backendRefs:
    - name: minecraft-helm
      port: 25565
