apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: nextcloud-oidc-config
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: nextcloud
  oidc:
    provider:
      issuer: "{{ .Values.authentikUrl }}/application/o/nextcloud/"
    clientIDRef:
      name: nextcloud-client-secret
    clientSecret:
      name: nextcloud-client-secret
    redirectURL: "https://nextcloud{{ .Values.envSuffix }}.jeremymr.dev/oauth2/callback"
    logoutPath: "/logout"
