apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: billing-service-db
  namespace: kleff-deployment
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 1Gi
  bootstrap:
    initdb:
      database: mydb
      owner: postgres
  superuserSecret:
    name: billing-db-credentials