apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: kleff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      # annotations:
      #   instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: billing-service
        paas: kleff
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
        - name: billing-service
          image: kleff.azurecr.io/billing-service:14ebbb811011581d83c312f9b97beeadf7fcd845
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-app
                  key: jdbc-uri
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-service-db-app
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: stripe_api_key
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: frontend_url
            - name: VITE_BACKEND_URL
              value: http://api-gateway.kleff-deployment.svc.cluster.local
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: kleff-deployment
spec:
  selector:
    app: billing-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
