apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:15.17
  instances: {{ .Values.cnpgInstances }}
  storage:
    size: {{ .Values.cnpgStorage }}
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector CASCADE
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi