apiVersion: v1
kind: Service
metadata:
  name: internal-gateway
  namespace: envoy-gateway-system
spec:
  type: ClusterIP
  selector:
    # These labels are stable and based on your Gateway name ("prod-web")
    gateway.envoyproxy.io/owning-gateway-name: prod-web
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 10080  # Standard Envoy HTTP port
    - name: https
      port: 443
      protocol: TCP
      targetPort: 10443 # Standard Envoy HTTPS port

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: kleff-deployment
spec:
  type: ExternalName
  externalName: internal-gateway.envoy-gateway-system.svc.cluster.local
  ports:
    - name: http
      port: 80
      targetPort: 80