apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: kleff-deployment
spec:
  ports:
    - name: http
      port: 80
      targetPort: 10080
  selector:
    # Use the stable labels found in step 1
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
    gateway.envoyproxy.io/owning-gateway-name: prod-web