minecraftServer:
  eula: "TRUE"
  version: "LATEST"
  type: "VANILLA"
  difficulty: normal
  gameMode: survival
  motd: "Jeremy's Homelab Minecraft"
  memory: 4096M
  serviceType: ClusterIP

  rcon:
    enabled: true
    withGeneratedPassword: true

resources:
  requests:
    memory: 4Gi
    cpu: 1000m
  limits:
    memory: 4Gi

persistence:
  dataDir:
    enabled: true
    Size: 20Gi
    accessModes:
      - ReadWriteOnce
