minecraftServer:
  eula: "TRUE"
  version: "LATEST"
  type: "VANILLA"
  difficulty: easy
  gameMode: survival
  motd: "Jeremy's Homelab Minecraft - Dev"
  memory: 2048M
  serviceType: ClusterIP

  rcon:
    enabled: true
    withGeneratedPassword: true

resources:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 2Gi

persistence:
  dataDir:
    enabled: true
    Size: 5Gi
    accessModes:
      - ReadWriteOnce
