apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-chatbot-secrets
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: ai-chatbot-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI_API_KEY
    - secretKey: PINECONE_API_KEY
      remoteRef:
        key: PINECONE_API_KEY
    - secretKey: PINECONE_ENVIRONMENT
      remoteRef:
        key: PINECONE_ENVIRONMENT
    - secretKey: PINECONE_INDEX_NAME
      remoteRef:
        key: PINECONE_INDEX_NAME
