apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store-kleff 
    kind: ClusterSecretStore
  target:
    name: authentik-secrets-store 
    creationPolicy: Owner
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: AUTHENTIK_SECRET_KEY

  - secretKey: POSTGRESQL_PASSWORD
    remoteRef:
      key: DB_PASSWORD 

  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: REDIS_PASSWORD