apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-kleff-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-kleff
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: CLOUDFLARE_API_TOKEN