apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: global-acr-creds
spec:
  externalSecretName: acr-creds
  namespaceSelector:
    matchLabels:
      managed-by: paas-backend # This matches the label your Go code adds!
  refreshInterval: "1h"
  externalSecretSpec:
    secretStoreRef:
      name: doppler-secret-store-kleff
      kind: ClusterSecretStore
    target:
      name: acr-creds
      template:
        engineVersion: v2
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "{{ .acr_server }}": {
                  "username": "{{ .acr_username }}",
                  "password": "{{ .acr_password }}",
                  "auth": "{{ (printf "%s:%s" .acr_username .acr_password) | b64enc }}"
                }
              }
            }
        type: kubernetes.io/dockerconfigjson
    data:
    - secretKey: acr_server
      remoteRef:
        key: ACR_SERVER
    - secretKey: acr_username
      remoteRef:
        key: ACR_USERNAME
    - secretKey: acr_password
      remoteRef:
        key: ACR_PASSWORD1