apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-db-credentials
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: user-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: USER_DB_USERNAME
  - secretKey: password
    remoteRef:
      key: USER_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: project-management-db-credentials
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: project-management-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: PROJECT_MANAGEMENT_DB_USERNAME
  - secretKey: password
    remoteRef:
      key: PROJECT_MANAGEMENT_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deployment-service-db-credentials
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: deployment-service-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: DEPLOYMENT_DB_USERNAME
  - secretKey: password
    remoteRef:
      key: DEPLOYMENT_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: billing-db-credentials
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: billing-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: BILLING_DB_USERNAME
  - secretKey: password
    remoteRef:
      key: BILLING_DB_PASSWORD