apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: project_management_db_password
    remoteRef:
      key: PROJECT_MANAGEMENT_DB_PASSWORD
  - secretKey: user_db_password
    remoteRef:
      key: USER_DB_PASSWORD
  - secretKey: deployment_db_password
    remoteRef:
      key: DEPLOYMENT_DB_PASSWORD
  - secretKey: billing_db_password
    remoteRef:
      key: BILLING_DB_PASSWORD
  - secretKey: stripe_api_key
    remoteRef:
      key: STRIPE_API_KEY
  - secretKey: frontend_url
    remoteRef:
      key: FRONTEND_URL
  - secretKey: vite_backend_url
    remoteRef:
      key: VITE_BACKEND_URL
  - secretKey: authentik_admin_token
    remoteRef:
      key: AUTHENTIK_ADMIN_TOKEN
