apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: kleff-deployment
spec:
  secretStoreRef:
    name: doppler-secret-store-kleff
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: stripe_api_key
    remoteRef:
      key: STRIPE_API_KEY
  - secretKey: frontend_url
    remoteRef:
      key: FRONTEND_URL
  - secretKey: vite_backend_url
    remoteRef:
      key: VITE_BACKEND_URL
  - secretKey: authentik_admin_token
    remoteRef:
      key: AUTHENTIK_ADMIN_TOKEN
  - secretKey: default_admin_email
    remoteRef:
      key: DEFAULT_ADMIN_EMAIL
