apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: mimir
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-discord-webhook
    creationPolicy: Owner
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: ALERTMANAGER_DISCORD_ALERTS_WEBHOOK
