apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-rules-persistent-volumes
  namespace: mimir
data:
  persistent-volumes.yaml: |
    groups:
      - name: persistent-volumes
        rules:
          - alert: PersistentVolumeHighUsage
            expr: |
              (
                kubelet_volume_stats_used_bytes
                / kubelet_volume_stats_capacity_bytes
              ) > 0.75
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "PVC {{ $labels.persistentvolumeclaim }} above 80% in {{ $labels.namespace }}"
              description: >-
                PersistentVolumeClaim {{ $labels.persistentvolumeclaim }}
                in namespace {{ $labels.namespace }} is
                {{ $value | humanizePercentage }} full.
