apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-admin-token
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: garage-admin-token
    creationPolicy: Owner
  data:
    - secretKey: adminToken
      remoteRef:
        key: GARAGE_ADMIN_TOKEN
    - secretKey: rpcSecret
      remoteRef:
        key: GARAGE_RPC_SECRET
