apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: nextcloud-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "17"
spec:
  forProvider:
    source: Inline
    module: |
      terraform {
        required_providers {
          authentik = {
            source  = "goauthentik/authentik"
            version = "~> 2025.2.0"
          }
        }
      }

      variable "authentik_url" {
        type = string
      }

      variable "authentik_token" {
        type      = string
        sensitive = true
      }

      variable "authorization_flow" {
        type = string
      }

      variable "invalidation_flow" {
        type = string
      }

      provider "authentik" {
        url   = var.authentik_url
        token = var.authentik_token
      }

      data "authentik_flow" "authorization" {
        slug = var.authorization_flow
      }

      data "authentik_flow" "invalidation" {
        slug = var.invalidation_flow
      }

      resource "authentik_provider_oauth2" "nextcloud" {
        name               = "Nextcloud"
        authorization_flow = data.authentik_flow.authorization.id
        invalidation_flow  = data.authentik_flow.invalidation.id
        client_type        = "confidential"
        client_id          = "nextcloud"

        allowed_redirect_uris = [
          {
            matching_mode = "strict"
            url           = "https://nextcloud{{ .Values.envSuffix }}.jeremymr.dev/oauth2/callback"
          }
        ]
      }

      resource "authentik_application" "nextcloud" {
        name               = "Nextcloud"
        slug               = "nextcloud"
        protocol_provider  = authentik_provider_oauth2.nextcloud.id
        policy_engine_mode = "any"
      }

      output "client-id" {
        value = authentik_provider_oauth2.nextcloud.client_id
      }

      output "client-secret" {
        value     = authentik_provider_oauth2.nextcloud.client_secret
        sensitive = true
      }

    vars:
      - key: authentik_url
        value: "https://auth{{ .Values.envSuffix }}.jeremymr.dev"
      - key: authorization_flow
        value: "default-provider-authorization-explicit-consent"
      - key: invalidation_flow
        value: "default-provider-invalidation-flow"
    env:
      - name: TF_VAR_authentik_token
        secretKeyRef:
          namespace: crossplane-system
          name: authentik-api-token
          key: token

  writeConnectionSecretToRef:
    name: nextcloud-client-secret
    namespace: nextcloud

  providerConfigRef:
    name: terraform-config
