apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kleff-io-cert
  namespace: envoy-gateway-system
spec:
  secretName: kleff-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "kleff.io"
  - "*.kleff.io"