apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-password
  namespace: couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: couchdb-creds

  data:
    - secretKey: couchdb-password
      remoteRef:
        key: COUCHDB_PASSWORD
