apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: tailscale-creds

  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_OAUTH_CLIENTID

    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_OAUTH_CLIENTKEY
