apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: kleff-deployment
spec:
  ports:
  - port: 5432
  selector:
    app: user-db
  clusterIP: None 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  namespace: kleff-deployment
spec:
  serviceName: "user-db"
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: user_service
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: user_service
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: user_db_password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      storageClassName: longhorn 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi