apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: user-db
  namespace: kleff-deployment
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 1Gi
  bootstrap:
    initdb:
      database: user_service
      owner: user_service
  superuserSecret:
    name: user-db-credentials